### PR TITLE
Stop sidereal drift from smearing out the grid

### PR DESCRIPTION
**Pull request by a-r-williamson**
This PR is to address some issues raised in #54, specifically:

- [x] Remove the time smearing in the sky grid plot
- [x] Have the sky grid plot wrap correctly, i.e. x-axis should not start/end at 0/360 degrees when a grid crosses the meridian

### CODE REVIEW

**Comment by a-r-williamson** [comment]
The changes in 0871230e94f61cd538e2f5495c1f7ed8cbb5a083 turn...
image
...into...
image

**Comment by pannarale** [comment]
We could also plot the first and last set of points in 2 different color/symbol codes.  What do you think?

**Comment by a-r-williamson** [comment]
The changes in 16ef39dcce8a9a034e2374a4d87ce35f86a199ba turn...
image
...into...
image

**Comment by a-r-williamson** [comment]
Added grid
image

**Comment by a-r-williamson** [comment]
@pannarale 
> We could also plot the first and last set of points in 2 different color/symbol codes. What do you think?

Do you mean showing the span of the drift over the whole analysis period? How useful/informative will that be?

**Comment by pannarale** [comment]
I guess, it would be good to somehow remind/tell/inform whoever is viewing the page that there is a relative motion between Earth and the sky patch (the drift you mention).  Not sure what the best way of representing this is.  I agree it wasn't the original smeared plot :-)

**Comment by a-r-williamson** [comment]
Ok, I'll play around with it later and see if there's a good way.

I am considering colouring the points according to antenna response.

**Comment by pannarale** [comment]
I looked at the changes so far and they are fine.  The changes to address the issue, so I am happy to merge.  We can open a new issue for the other improvement(s).

**Pull request merged**
